apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  component: minio
  app.kubernetes.io/component: minio
  app.kubernetes.io/instance: minio
  app.kubernetes.io/name: minio
  app.kubernetes.io/part-of: minio

resources:
- deployment.yaml
- pvc.yaml
- route.yaml
- service.yaml
- setup-secret-job.yaml
- setup-buckets-job.yaml
