FROM registry.access.redhat.com/ubi8/nodejs-18 as build

WORKDIR /usr/src/app

COPY --chown=1001:0 package*.json .
RUN npm ci
COPY --chown=1001:0 . .
RUN npm run build

FROM registry.access.redhat.com/ubi8/nginx-120

# ADD /nginx.conf "${NGINX_CONF_PATH}"
COPY --chown=1001:0 --from=build /usr/src/app/dist .

RUN ls -al

CMD nginx -g "daemon off;"