FROM registry.access.redhat.com/ubi8/nodejs-18 as build

WORKDIR /usr/src/app

# Install dependencies and enable a cached deps layer
COPY --chown=1001:0 package*.json .
RUN npm ci

# Copy other sources and build the application
COPY --chown=1001:0 . .
RUN npm run build

FROM registry.access.redhat.com/ubi8/nginx-120

COPY --chown=1001:0 --from=build /usr/src/app/dist .
COPY --chown=1001:0 nginx.conf .

# envsubst replaces the RPS_BACKEND_HOST in the template nginx.conf and writes
# it to the $NGINX_CONF_PATH (this variable is defined in the base image)
CMD envsubst '$RPS_BACKEND_HOST' < 'nginx.conf' > $NGINX_CONF_PATH && nginx -g "daemon off;"